_target_: src.models.model_module.ModelModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00015
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.factory.build_3d_architecture
  model_name: unetplusplus

# compile model for faster training with pytorch 2.0
compile: false
